### ISSUE TITLE
remove reference to Delaunay Triangulation in THIRD_PARTY

### ISSUE THREAD

**Issue by morishuz** [heremaps/tin-terrain#18]
this is no longer part of the project and should be removed

> - Delaunay Triangulation algorithm from OSM Wave by Per Liedman in files:
>     src/Delaunay.cpp
>     include/tngrnd/Delaunay.h

**Comment by morishuz** [comment]
fixed by https://github.com/heremaps/tin-terrain/pull/19/commits/40a6e426f57b34a79137b98899cb9df2d24901be

**Comment by adrpar** [comment]
I am closing this issue, since it already has been resolved (see comment above).
