### ISSUE TITLE
Mesh2Raster::rasterise does costly calculations for a DEBUG message

### ISSUE THREAD

**Issue by cleeus** [heremaps/tin-terrain#2]
https://github.com/heremaps/tin-terrain/blob/4e036cc9d1322d3029ab7eda6a78b82647b1220e/src/Mesh2Raster.cpp#L223-L245

This #if true block looks like debug code and it seems to serve no other purpose than creating a debug message. I think we can do without it.

**Comment by morishuz** [comment]
Yes, It is indeed debug code (checks for holes in the render output) and should be off in release, but I don’t think it adds significantly to the runtime of the rasteriser. I would guess around 10%.

**Comment by morishuz** [comment]
fixed by [b018ed4](https://github.com/heremaps/tin-terrain/pull/13/commits/b018ed4e22b158b1400d1e666b4b1fd923694df3)
