### ISSUE TITLE
CMake might find wrong GDAL library

### ISSUE THREAD

**Issue by adrpar** [heremaps/tin-terrain#22]
There is an issue with the cmake provided `FindGDAL.cmake` script (see https://gitlab.kitware.com/cmake/cmake/issues/17771, even though they claim things are fixed, they are not).

The issue mainly is, that FindGDAL determines the right location of the GDAL library though `gdal-config`, however fails to use the insights gained from that procedure. It is then using `find_library` to search for gdal again, and then obviously derails...

The best would be to fix the `FindGDAL.cmake` file or provide our own in the repository. However for the moment, I propose to just update the README file accordingly (see my PR).

**Comment by adrpar** [comment]
See PR https://github.com/heremaps/tin-terrain/pull/23

**Comment by delfrrr** [comment]
Actually I just run into this problem!
