### ISSUE TITLE
Setup CI with Travis

### ISSUE THREAD

**Issue by delfrrr** [heremaps/tin-terrain#25]
- build a docker image
- check formatting (clang-format)
- build with clang (release/debug)
- build with gcc (release/debug)
- build with fsanitize

**Comment by delfrrr** [comment]
check this as the reference https://github.com/mapbox/hpp-skel/blob/master/.travis.yml

**Comment by adrpar** [comment]
PR: https://github.com/heremaps/tin-terrain/pull/39

**Comment by adrpar** [comment]
PR now contains all the mentioned tests.

**Comment by adrpar** [comment]
Closing this, since PR got merged.
