### ISSUE TITLE
Tiling Issue - No Zoom Level 1 or 0

### ISSUE THREAD

**Issue by BTolputt** [heremaps/tin-terrain#51]
Using a freely available height DEM from Earth Explorer (ASTGTM2_S37E148_dem) - dem2tintiles results in a truncated set of zoom levels. Level 1 results in the message below, no level 0 is generated.

```
after clipping: 0 triangles in tile
WARN cmd.cpp:206 raster on zoom level 0 empty, cannot create tiles, proceeding...
```
Zoom levels 2-6 are only generated if I force them by setting "max-zoom".
[ASTGTM2_S37E148_dem.tif.zip](https://github.com/heremaps/tin-terrain/files/2805987/ASTGTM2_S37E148_dem.tif.zip)

**Comment by fester** [comment]
Thanks for reporting it.
There indeed was a bug with zoom level estimation caused by an attempt to simplify code and I rolled it back to fix it. However, in the dataset you mention, tin-terrain should not generate any tiles above zoom level number 7. After resampling the input raster for zoom levels about 7th, it's size becomes less than 128 pixels on a large side and this is sort of an arbitrary threshold for the downscaling. In the new commit to the normals branch I added a message to inform about min and max zoom levels that will be used.

**Comment by BTolputt** [comment]
@fester - Whilst I understand this on a technical level (appreciate the background on reason why it was failing), the sole application (that I am aware of) for quantised tiles is CesiumJS which cannot work without a hierarchy of tiles up to (& including) level 0. The open-source Cesium Terrain Builder application allows for this to be built missing data for this very reason.

Unless I am missing something, quantised tiles are useless outside Cesium and perhaps we can/should create a feature request to enable these empty parent tiles to be created with "sea level" data if we don't have enough real data for downscaling?

**Comment by nik-garmash** [comment]
@BTolputt It's true that Cesium cannot render arbitrary zoom level without loading every parent level, it's on their roadmap to fix this.

> Support skipping intermediate tiles in the tile pyramid.  For example, if the camera starts zoomed into, we should be able to load the high-res tiles immediately rather than refining down through the tree first and waiting at each level for the previous level to complete.

There are a couple of workarounds, please take a look at [Quantized Mesh Viewer](https://github.com/heremaps/quantized-mesh-viewer). There, missing tiles are just mocked with plane geometry in runtime. 

You can use the viewer to debug tiles generated by tin-terrain or you can create custom surface provider similar to [the one in the viewer](https://github.com/heremaps/quantized-mesh-viewer/blob/master/src/map/surface-provider.js).
