### ISSUE TITLE
Corners are inserted in the output mesh even if they are no data values

### ISSUE THREAD

**Issue by salvioli** [heremaps/tin-terrain#58]
I tried to transform a DEM from HiRise data which is distributed as GTiff format. The input DEM is available [here](https://www.uahirise.org/dtm/dtm.php?ID=ESP_036925_1985).
This file includes several no-data value points which include the four corners of the raster DEM and dem2tin seems to add to the output obj the four corners even if these are no-data values.

The following is the output of the program after processing the DEM:
![image](https://user-images.githubusercontent.com/5619715/56094334-ba680380-5ed3-11e9-9edd-c64527399257.png)

**Comment by fester** [comment]
Insertion of vertices in place of nodata pixels at corners is a part of meshing alorithm and can't be fixed withou making significant changes to it. There's no easy way to solve this, simplest way may be just rotating the raster.

**Comment by salvioli** [comment]
Sorry for bothering more on this topic, wouldn't we be able to simply post-process the mesh removing all vertices which correspond to no-data values on the raster?
