### ISSUE TITLE
Error while building and installing 

### ISSUE THREAD

**Issue by Girishchandra-Yendargaye** [heremaps/tin-terrain#77]
error: parameter declared ‘auto’
         std::for_each(begin, end, [this](const auto& v) { add(v); });
 error: ‘v’ was not declared in this scope
         std::for_each(begin, end, [this](const auto& v) { add(v); });
 error: ‘make_unique’ is not a member of ‘std’
     TileMaker() : m_mesh(std::make_unique<Mesh>()) {}
 error: expected primary-expression before ‘>’ token
     TileMaker() : m_mesh(std::make_unique<Mesh>()) {}
 error: expected primary-expression before ‘)’ token
     TileMaker() : m_mesh(std::make_unique<Mesh>()) {}

**Comment by kiner-shah** [comment]
`for_each` was introduced in C++ 17 as per [this link](https://en.cppreference.com/w/cpp/algorithm/for_each). And `make_unique` in C++ 14 as per [this link](https://en.cppreference.com/w/cpp/memory/unique_ptr/make_unique).
Where exactly are you getting this error?

**Comment by crohr88** [comment]
I had something similar while compiling. I was inadvertently using an old compiler (4.8.5) for both boost and tin-terrain. Everything behaved correctly under GCC 8.3.0.

**Comment by Girishchandra-Yendargaye** [comment]
> error: parameter declared ‘auto’ std::for_each(begin, end, [this](const auto& v) { add(v); }); error: ‘v’ was not declared in this scope std::for_each(begin, end, [this](const auto& v) { add(v); }); error: ‘make_unique’ is not a member of ‘std’ TileMaker() : m_mesh(std::make_unique()) {} error: expected primary-expression before ‘>’ token TileMaker() : m_mesh(std::make_unique()) {} error: expected primary-expression before ‘)’ token TileMaker() : m_mesh(std::make_unique()) {}

Yes after changing compiler it worked.
